% SPDX-License-Identifier: PMPL-1.0-or-later
% descriptive_verify.m — Independent verification of descriptive statistics.
%
% WHY OCTAVE AND NOT JULIA?
% ─────────────────────────
% StatistEase computes in Julia. Aspasia verifies in Octave. Using the same
% language would mean the same numerical library, the same floating-point
% paths, the same bugs. A genuine second opinion requires a genuinely
% different implementation. Octave uses different linear algebra backends
% (LAPACK/BLAS vs Julia's OpenBLAS), different sorting algorithms, different
% statistical primitives. If both languages produce the same answer via
% different code paths, that answer is far more trustworthy than either alone.

function result = descriptive_verify(data, claimed)
  % DESCRIPTIVE_VERIFY  Cross-check claimed descriptive statistics.
  %
  %   result = descriptive_verify(data, claimed)
  %
  %   data    — numeric vector (the raw data)
  %   claimed — struct with fields from StatistEase output:
  %             .mean, .median, .std_dev, .variance, .min, .max,
  %             .q1, .q3, .skewness, .kurtosis, .n
  %
  %   result  — struct with:
  %             .verified    — logical, true if all checks pass
  %             .discrepancies — cell array of issues found
  %             .recomputed  — struct of independently computed values
  %             .tolerance   — floating-point tolerance used

  tolerance = 1e-10;
  discrepancies = {};

  % Independently compute everything
  n = length(data);
  m = mean(data);
  med = median(data);
  s = std(data);        % Octave std() uses N-1 by default (Bessel's correction)
  v = var(data);
  lo = min(data);
  hi = max(data);
  q1 = quantile(data, 0.25);
  q3 = quantile(data, 0.75);
  sk = skewness(data);
  ku = kurtosis(data);  % Octave: excess kurtosis (normal = 0)

  recomputed = struct( ...
    'n', n, ...
    'mean', m, ...
    'median', med, ...
    'std_dev', s, ...
    'variance', v, ...
    'min', lo, ...
    'max', hi, ...
    'q1', q1, ...
    'q3', q3, ...
    'skewness', sk, ...
    'kurtosis', ku ...
  );

  % Cross-check each claimed value
  checks = { ...
    'n',        n,   claimed.n; ...
    'mean',     m,   claimed.mean; ...
    'median',   med, claimed.median; ...
    'std_dev',  s,   claimed.std_dev; ...
    'variance', v,   claimed.variance; ...
    'min',      lo,  claimed.min; ...
    'max',      hi,  claimed.max; ...
    'q1',       q1,  claimed.q1; ...
    'q3',       q3,  claimed.q3; ...
    'skewness', sk,  claimed.skewness; ...
    'kurtosis', ku,  claimed.kurtosis ...
  };

  for i = 1:size(checks, 1)
    name = checks{i, 1};
    octave_val = checks{i, 2};
    claimed_val = checks{i, 3};

    if abs(octave_val - claimed_val) > tolerance
      msg = sprintf('DISCREPANCY in %s: claimed=%.15g, recomputed=%.15g, diff=%.2e', ...
                    name, claimed_val, octave_val, abs(octave_val - claimed_val));
      discrepancies{end+1} = msg;
    end
  end

  result = struct( ...
    'verified', isempty(discrepancies), ...
    'discrepancies', {discrepancies}, ...
    'recomputed', recomputed, ...
    'tolerance', tolerance, ...
    'engine', 'GNU Octave', ...
    'note', 'Independent recomputation using different numerical backend' ...
  );
end
